apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: homer-thebusbees
  name: homer-thebusbees
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: homer-thebusbees
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: homer-thebusbees
    spec:
      containers:
        - env:
            - name: GID
              value: "1000"
            - name: UID
              value: "1000"
          image: b4bz/homer
          name: homer-thebusbees
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: nfs-homer-thebusbees  
      dnsConfig:
        nameservers:
          - 8.8.8.8
          #volumeMounts:
          #  - mountPath: /www/assets
          #    name: homer-claim0
      restartPolicy: Always
      volumes:
        - name: nfs-homer-thebusbees
          nfs:
            server: 10.0.0.10
            path: /homelab/docker/homer-thebusbees
#        - name: homer-claim0
#          persistentVolumeClaim:
#            claimName: homer-claim0
---
#nodeport
apiVersion: v1
kind: Service
metadata:
    name: nodeport
    namespace: default
spec:
    type: NodePort
    selector:
        app: homer-thebusbees
    ports:
        - name: web
          port: 8080
          targetPort: web
          nodePort: 30001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-thebusbees-config-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
